/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("net.kyori.blossom") version "1.3.1"
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.dmulloy2.net/repository/public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    compileOnly("com.comphenix.protocol:ProtocolLib:5.1.0")
}

group = "net.playl.scccpdebris"
version = "1.6.4"
description = "scccpdebris"

tasks {
    processResources {
        val props = mapOf(
            "version" to version,
        )
        filesMatching("plugin.yml") {
            expand(props)
        }

    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.named("build") {
    finalizedBy("shadowJar")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
