name: scccpdebris-folia
main: net.playl.scccpdebris.Main
version: "${version}"
author: UnknownKE
api-version: 1.19
folia-supported: true
description: fix flawed part of the Minecraft multiplayer protocol

depend: [ProtocolLib]
